server:
  port: 8888
  servlet:
    context-path: /member
    application-display-name: member-service
spring:
  output:
    ansi:
      enabled: always
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: train
    password: Blkcor@dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: member
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      github:
        blkcor:
          mapper: trace

test:
  name: rainbow