spring:
  output:
    ansi:
      enabled: always
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes[0]:
        id: member-service
#        uri: http://localhost:8888
        uri: lb://member
        predicates[0]: Path=/member/**
      routes[1]:
        id: business-service
        uri: lb://business
        predicates[0]: Path=/business/**
      routes[2]:
        id: batch-service
        uri: lb://batch
        predicates[0]: Path=/batch/**
# 路由转发 将/member/** 转发到 member模块
server:
  port: 9999